
BOOTMAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
NKRO_ENABLE = yes
BACKLIGHT_ENABLE = no
MIDI_ENABLE = no
AUDIO_ENABLE = no
UNICODE_ENABLE = yes
BLUETOOTH_ENABLE = no
RGBLIGHT_ENABLE = no

SLEEP_LED_ENABLE = no 

ifndef QUANTUM_DIR
	include ../../../../Makefile
endif
